version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: registry
      POSTGRES_USER: registry
      POSTGRES_PASSWORD: registry
    ports:
      - "5432:5432"

  api:
    build: ./api
    ports:
      - "8080:8000"
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: registry
      DB_USERNAME: registry
      DB_PASSWORD: registry
    depends_on:
      - postgres

  ui:
    build: ./ui
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: http://localhost:8080
    depends_on:
      - api
